name: Test, lint and build
on:
    push:
        branches:
            - main
jobs:
    test:
        runs-on: macos-latest

        steps:
            - name: clone repository
              uses: actions/checkout@v4
            
            - name: setup flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: '3.29.0'
                channel: 'stable'
            
            - run: flutter --version
            - run: flutter pub get

            - name: Check code formatting 
              run: |
                flutter analyze
                dart format --set-exit-if-changed .

            - run: flutter test
            - run: flutter test --coverage 
            
            - name: Setup LCOV
              uses: hrishikesh-kadam/setup-lcov@v1
    
            - name: Report Code Coverage
              uses: zgosalvez/github-actions-report-lcov@v3
              with:
                coverage-files: coverage/lcov.info
                minimum-coverage: 0
                artifact-name: code-coverage-report
                github-token: ${{ secrets.GITHUB_TOKEN }}



            


        



