name: Test, lint and build
on:
    push:
        branches:
            - main
jobs:
    test:
        runs-on: macos-latest

        steps:
            - name: clone repository
              uses: actions/checkout@v4
            - name: setup flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: '3.29.0'
                channel: 'stable'
            
            - run: flutter --version
            - run: flutter pub get

            - name: Check code formatting 
              run: |
                flutter analyze
                dart format --set-exit-if-changed .

            - run: flutter test
            - run: flutter test --coverage 
            
            - name: upload coverage to Codecov
              uses: codecov/codecov-action@v5
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                files: ./coverage/lcov.info




            


        



